# Generated by Django 4.2 on 2022-07-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('poster', models.IntegerField()),
                ('trailer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('realedate', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('user_post', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
