# Generated by Django 4.2 on 2022-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovie',
            name='poster',
            field=models.CharField(max_length=100),
        ),
    ]
