# Generated by Django 4.2 on 2022-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_addmovie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovie',
            name='status',
            field=models.IntegerField(default=1, verbose_name=False),
            preserve_default=False,
        ),
    ]
